management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

info:
  app:
    name: spring-boot-actuator
    version: 2.1.2